"""create researches

Revision ID: 8f793094c151
Revises: a7c3e5f19d02
Create Date: 2026-09-04 16:44:40.523035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f793094c151'
down_revision: Union[str, Sequence[str], None] = 'a7c3e5f19d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('resarch', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_table('researches')
    # ### end Alembic commands ###
